### ISSUE TITLE
Rviz problem

### ISSUE THREAD

**Issue by haritsahm** [ROBOTIS-GIT/ROBOTIS-OP3-Common#1]
what is wrong with my rviz? there's no transform from [   ] to [body_link] and the robot display is weird. Thankyou

![issues](https://user-images.githubusercontent.com/26606913/31342803-ff5c2db2-ad37-11e7-8243-dcc2ea1b95d9.png)

**Comment by kaym9n** [comment]
It looks tf message does not exist.
To make tf message need joint states messge from ```op3_manager```. You need to execute ```op3_manager``` and check again. 
If you couldn't execute ```op3_manager```, modify ```robotis_op3_display.launch``` like below and run the launch file. (It's the method to use a fake joint_states.)
```
<launch>
  <param name="robot_description"
    command="$(find xacro)/xacro.py '$(find robotis_op3_description)/urdf/robotis_op3.urdf.xacro'" />

  <!-- Send fake joint values -->
  <node name="joint_state_publisher" pkg="joint_state_publisher" type="joint_state_publisher">
    <param name="use_gui" value="TRUE"/>
    <rosparam param="/source_list">[/robotis/present_joint_states]</rosparam>
  </node>

  <!-- Combine joint values -->
  <node name="robot_state_publisher" pkg="robot_state_publisher" type="state_publisher"/>

  <!-- Show in Rviz   -->
  <node name="rviz" pkg="rviz" type="rviz" args="-d $(find robotis_op3_description)/launch/op.rviz"/>

</launch>
```

**Comment by haritsahm** [comment]
Hi, after i execute op3_manager, the problem still exist
![issues](https://user-images.githubusercontent.com/26606913/31425743-b8296190-ae8a-11e7-9186-7f1d658c8d86.png)

and here is the tf-tree
![tftree](https://user-images.githubusercontent.com/26606913/31425806-f9947750-ae8a-11e7-831f-5d143f51edbb.png)

i've tried using other branch but still the robot display is weird

**Comment by kaym9n** [comment]
I'm sorry in your inconvenience.
Could you refer to this issue(https://github.com/ROBOTIS-GIT/ROBOTIS-OP3/issues/6)?

**Comment by haritsahm** [comment]
i don't think the problem is the host name / subscribe topics, because when i run thormang3 or robotis op2 everything works fine. I think the problem is the link or fixed frame, and i don't really understand about rviz or urdf. thank you

**Comment by robograffitti** [comment]
My result is also missing some parts... (Fixed Frame is set to body_link)

I executed the following 2 commands:
1. $ roslaunch op3_manager op3_manager.launch
2. $ roslaunch robotis_op3_description robotis_op3_display.launch

![screenshot from 2017-10-12 18-41-03](https://user-images.githubusercontent.com/5218765/31489889-2e2fbc02-af7d-11e7-9914-885893e953f9.png)

**Comment by kaym9n** [comment]
It's my rviz screen.
![robotis_op3_rviz](https://user-images.githubusercontent.com/16040148/31528124-93a9a69e-b00c-11e7-9557-da1fd7ffe41b.png)

I suspect this issue in terms of network and timing.
(Reference : [Timing issues](http://wiki.ros.org/ROS/NetworkSetup#Timing_issues.2C_TF_complaining_about_extrapolation_into_the_future.3F))
I'd recommend you to run the following instructions from the ROBOTIS-OP3 PC.

1. Connect the keyboard, mouse and monitor to OP3.
2. Kill the demo  
```$ sudo service OP3-demo stop```  

3. Execute op3_manager  
``` $ roslaunch op3_manager op3_manager.launch```  

4. Execute robotis_op3_description
``` $ roslaunch robotis_op3_description robotis_op3_display.launch```  

5. If it works, it's a timing issue.

**Comment by haritsahm** [comment]
i actually don't have the OP3 robot. I just want to try the rviz and gazebo, but i will try that and give the result later. Thank you so much

**Comment by kaym9n** [comment]
I understood.
We still do not fully support gazebo. I hope it will be supported soon.

**Comment by robograffitti** [comment]
@haritsahm I resolved this issue by building all the OP3 codes with catkin make. try:

$ `roscd && cd ..`
$ `catkin_make`
