### ISSUE TITLE
Problem with Error [Param.cc:451] Unable to set value [-inf -inf -inf 0.007743 -0.097959 0.502899] for key[pose]

### ISSUE THREAD

**Issue by culdo** [ROBOTIS-GIT/ROBOTIS-OP3-Common#11]
Hi, 
sorry for my bad English, 
I got gazebo error below, while I click the Get up(Front) or Push up motion using op3_gui_demo, then the op3 got wrong pose.
![image](https://user-images.githubusercontent.com/26900749/50415611-f4df5f00-0856-11e9-879c-0eb6b42cb498.png)
I have installed newest packages for simulating OP3 in Gazebo.
I started gazebo with:
`roslaunch op3_gazebo robotis_world.launch`
then start manger:
`roslaunch op3_manager op3_gazebo.launch`
Finally, open gui demo:
`roslaunch op3_gui_demo op3_demo.launch`

Thank you for help!

**Comment by kaym9n** [comment]
Hi,

We made motions for ROBOTIS-OP3 under the real world.
In gazebo, some of motions may not work correctly.
I think it's a friction problem. We do not fully support gazebo.

I'm sorry that I have to tell you it's normal under the current situation.

Regards, 
Kayman

**Comment by kaym9n** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
