### ISSUE TITLE
difficult to understand the urdf

### ISSUE THREAD

**Issue by yuan0623** [ROBOTIS-GIT/ROBOTIS-OP3-Common#12]
Hi, I have some dynamic computing task which require the accurate inertial and kinematic information about OP3. When I look into the urdf fold, I have trouble to understand it. I used to get one urdf file with complete information about one robot(such as Nao), but now I get several files(which is fine, I can put them together into one file).
The real problem is that: when I look into the file(such as robotis_op3.structure.rarm.xacro) and find
>   <xacro:insert_inertia_l_el_link />

, then I have no idea where to find the corresponding inertial value for this link. Can you give me some advice on it?

**Comment by kaym9n** [comment]
Hi,

We made urdf files according to the [xacro](http://wiki.ros.org/xacro).
You can find inertia in [the inertia file](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Common/blob/master/op3_description/urdf/robotis_op3.inertia.xacro).

**Comment by yuan0623** [comment]
Thanks so much. I've made it into one urdf file myself. May I ask why you guy choose to make it into separate files instead of one? What's the advantage of doing that?

**Comment by kaym9n** [comment]
It is better to understand than to use a single urdf file. 
and it is also good for maintenance.

**Comment by HPaper** [comment]
This issue will be closed since there were no actions for a while. You can reopen this issue to show this issue to the users whenever. Thanks.
