### ISSUE TITLE
Split ll6.stl and rl6.stl into 2 pieces

### ISSUE THREAD

**Issue by robograffitti** [ROBOTIS-GIT/ROBOTIS-OP3-Common#3]
I'm trying to add a force sensor plugin on the joint in between foot plate and ankle roll link. However, these two parts are glued together. 

Can you split the part into 2 pieces? This will be very helpful to configure measurement range of force sensors before buying real sensors for a real robot.

**Comment by kaym9n** [comment]
[op3_foot_mass_property.zip](https://github.com/ROBOTIS-GIT/ROBOTIS-OP3-Common/files/1456746/op3_foot_mass_property.zip)

I think it can help you.
If you have extra supports, ask me again.

ps. You can find the hardware material(stp file) in [ROBOTIS-OP-Series-Data](https://github.com/ROBOTIS-GIT/ROBOTIS-OP-Series-Data/blob/master/ROBOTIS-OP3/Hardware/Mechanics/Part/ROBOTIS-OP3_part_asm.stp)

**Comment by robograffitti** [comment]
Thanks! I'm trying to implement it now.

**Comment by robograffitti** [comment]
I created the branch to run the gazebo simulation with ft sensors of its foot.
https://github.com/yoshimalucky/ROBOTIS-OP3-Common/tree/gazebo-ft-sensor
